"""Sans-I/O HTTP/2 protocol library for Python, backed by libnghttp2."""

from ._core import Connection, pack_settings_payload
from ._version import __version__
from .config import Configuration, Role
from .enums import ErrorCode, FrameType, Setting
from .events import (
    AltSvcReceived,
    DataReceived,
    Event,
    FrameNotSent,
    GoAwayReceived,
    InformationalResponseReceived,
    OriginReceived,
    PingAcknowledged,
    PingReceived,
    PriorityUpdateReceived,
    PushedStreamReceived,
    RequestReceived,
    ResponseReceived,
    SettingsAcknowledged,
    SettingsReceived,
    StreamClosed,
    StreamReset,
    TrailersReceived,
    WindowUpdated,
)
from .exceptions import (
    ConnectionClosingError,
    ConnectionProtocolError,
    ConnectionStateError,
    DenialOfServiceError,
    InternalError,
    NGH2Error,
    NoAvailableStreamIDError,
    ProtocolError,
    PushDisabledError,
    StreamProtocolError,
    StreamUnavailableError,
)
from .types import Header, NeverIndexedHeader, Priority

__all__ = [
    "AltSvcReceived",
    "Configuration",
    "Connection",
    "ConnectionClosingError",
    "ConnectionProtocolError",
    "ConnectionStateError",
    "DataReceived",
    "DenialOfServiceError",
    "ErrorCode",
    "Event",
    "FrameNotSent",
    "FrameType",
    "GoAwayReceived",
    "Header",
    "InformationalResponseReceived",
    "InternalError",
    "NGH2Error",
    "NeverIndexedHeader",
    "NoAvailableStreamIDError",
    "OriginReceived",
    "PingAcknowledged",
    "PingReceived",
    "Priority",
    "PriorityUpdateReceived",
    "ProtocolError",
    "PushDisabledError",
    "PushedStreamReceived",
    "RequestReceived",
    "ResponseReceived",
    "Role",
    "Setting",
    "SettingsAcknowledged",
    "SettingsReceived",
    "StreamClosed",
    "StreamProtocolError",
    "StreamReset",
    "StreamUnavailableError",
    "TrailersReceived",
    "WindowUpdated",
    "__version__",
    "pack_settings_payload",
]
