from collections.abc import Iterable, Mapping, Sequence
from typing import TypeAlias

from .config import Configuration, Role
from .enums import Setting
from .events import Event
from .types import Header, Priority

SettingsInput: TypeAlias = Mapping[int, int] | Mapping[Setting, int]

def pack_settings_payload(settings: SettingsInput) -> bytes: ...

class Connection:
    def __init__(
        self,
        role: Role,
        config: Configuration | None = None,
    ) -> None: ...
    @property
    def role(self) -> Role: ...
    @property
    def config(self) -> Configuration: ...
    def initiate_connection(
        self,
        settings: SettingsInput | None = None,
    ) -> None: ...
    def initiate_upgrade(
        self,
        settings_payload: bytes,
        *,
        local_settings: SettingsInput | None = None,
        head_request: bool = False,
    ) -> None: ...
    def receive_data(self, data: bytes | bytearray | memoryview) -> None: ...
    def events(self) -> list[Event]: ...
    def data_to_send(self, amount: int | None = None) -> bytes: ...
    def send_request(
        self,
        headers: Sequence[Header],
        *,
        end_stream: bool = False,
    ) -> int: ...
    def send_response(
        self,
        stream_id: int,
        headers: Sequence[Header],
        *,
        end_stream: bool = False,
    ) -> None: ...
    def send_informational_response(
        self,
        stream_id: int,
        headers: Sequence[Header],
    ) -> None: ...
    def send_trailers(self, stream_id: int, headers: Sequence[Header]) -> None: ...
    def send_push_promise(
        self,
        stream_id: int,
        headers: Sequence[Header],
    ) -> int: ...
    def send_data(
        self,
        stream_id: int,
        data: bytes | bytearray | memoryview,
        *,
        end_stream: bool = False,
    ) -> None: ...
    def end_stream(self, stream_id: int) -> None: ...
    def reset_stream(self, stream_id: int, error_code: int = 0x08) -> None: ...
    def update_settings(self, settings: SettingsInput) -> None: ...
    def ping(self, opaque_data: bytes = ...) -> None: ...
    def send_goaway(
        self,
        error_code: int = 0,
        *,
        last_stream_id: int | None = None,
        debug_data: bytes = b"",
    ) -> None: ...
    def send_shutdown_notice(self) -> None: ...
    def terminate_connection(
        self,
        error_code: int = 0,
        *,
        last_stream_id: int | None = None,
    ) -> None: ...
    def acknowledge_received_data(self, amount: int, stream_id: int) -> None: ...
    def send_priority_update(self, stream_id: int, field_value: bytes) -> bool: ...
    def set_stream_priority(
        self,
        stream_id: int,
        priority: Priority,
        *,
        ignore_client_signal: bool = False,
    ) -> bool: ...
    def get_stream_priority(self, stream_id: int) -> Priority | None: ...
    def send_alt_svc(
        self,
        field_value: bytes,
        *,
        stream_id: int = 0,
        origin: bytes = b"",
    ) -> None: ...
    def send_origins(self, origins: Iterable[bytes]) -> None: ...
    @property
    def want_read(self) -> bool: ...
    @property
    def want_write(self) -> bool: ...
    @property
    def next_stream_id(self) -> int: ...
    @property
    def can_send_request(self) -> bool: ...
    def pending_data(self, stream_id: int | None = None) -> int: ...
    @property
    def remote_window_size(self) -> int: ...
    def stream_remote_window_size(self, stream_id: int) -> int: ...
    @property
    def local_window_size(self) -> int: ...
    def stream_local_window_size(self, stream_id: int) -> int: ...
    @property
    def local_settings(self) -> dict[int, int]: ...
    @property
    def remote_settings(self) -> dict[int, int]: ...
